# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "Thimblr"
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JP Hastings-Spital"]
  s.date = "2011-11-05"
  s.description = "A webserver built to help you test tumblr themes as you edit them"
  s.email = "jphastings@gmail.com"
  s.executables = ["thimblr"]
  s.files = [
    "config/demo.yml",
    "config/settings.default.yaml",
    "lib/thimblr.rb",
    "lib/thimblr/importer.rb",
    "lib/thimblr/parser.rb",
    "public/assets/help.js",
    "public/assets/iphone-style-checkboxes.js",
    "public/assets/jquery-ui.js",
    "public/assets/jquery.js",
    "public/assets/main.js",
    "public/audio_player.swf",
    "public/audio_player_black.swf",
    "public/favicon.ico",
    "public/images/background.png",
    "public/images/blackbox-left.png",
    "public/images/blackbox-right.png",
    "public/images/content_bottom.png",
    "public/images/content_top.png",
    "public/images/download.png",
    "public/images/edit.png",
    "public/images/editors/bbedit.png",
    "public/images/editors/textedit.png",
    "public/images/editors/textmate.png",
    "public/images/goodies_background_gradient.png",
    "public/images/goodies_popup_bg.png",
    "public/images/highlight.png",
    "public/images/highlight_white.png",
    "public/images/input_bg.gif",
    "public/images/input_highlight_bg.png",
    "public/images/nav_arrow.png",
    "public/images/off.png",
    "public/images/on.png",
    "public/images/os/mac.png",
    "public/images/os/nix.png",
    "public/images/os/win.png",
    "public/images/preset.png",
    "public/images/site_notice_bg.png",
    "public/images/slider.png",
    "public/images/slider_center.png",
    "public/images/slider_left.png",
    "public/images/slider_right.png",
    "public/index.html",
    "public/stylesheets/help.css",
    "public/stylesheets/tumblr.css",
    "themes/101.html",
    "themes/Redux.html",
    "themes/Stationary.html",
    "views/help.erb",
    "views/menu.erb"
  ]
  s.homepage = "http://github.com/jphastings/Thimblr"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Helper for Tumblr theme editors"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0"])
      s.add_runtime_dependency(%q<launchy>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0"])
      s.add_dependency(%q<launchy>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0"])
    s.add_dependency(%q<launchy>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

